src/base/theme/_variables.scss, src/base/utils/define.js, src/components/splitview/components/splitView.js, src/components/splitview/styles/_shared.scss, src/showcase/screens/base/splitview/splitViewDemo.js
Arreglar problemas con el media querie
=> splitview media queries override

src/components/paginator/styles/_shared.scss, src/components/paginator/styles/ark.scss, src/components/paginator/styles/bootstrap.scss, src/components/paginator/styles/index.js, src/components/paginator/styles/material.scss
=> styles problem fixed

src/components/list/components/list.item.js, src/components/list/components/list.js
=> relative path change

src/components/signature/styles/_config.scss, src/components/signature/styles/_shared.scss, src/components/signature/styles/ark.scss, src/components/signature/styles/bootstrap.scss, src/components/signature/styles/index.js, src/components/signature/styles/material.scss, src/components/tabs/styles/_shared.scss, src/components/tabs/styles/ark.scss, src/components/tabs/styles/bootstrap.scss, src/components/tabs/styles/index.js, src/components/tabs/styles/material.scss
=> styles updated

src/components/modal/styles/material.scss, src/showcase/screens/base/modal/modalDemo.js
=> Material styles configuration added

src/components/input/README.rst, src/showcase/screens/base/input/inputDemo.js
=> Documentation README added

src/components/input/README.rst, src/showcase/screens/base/input/inputDemo.js
Arreglo de documentación del input
=> Documentation fixed

src/components/select/README.rst, tests/components/select/select.spec.js
Test arreglados y documentación añadida
=> Tests fixed and documentation added

src/showcase/screens/base/checkbox/checkboxDemo.js, tests/components/checkbox/checkbox-group.spec.js
Test de checkbox-group arreglado, falta el test del checkbox.spec.js
=> checkbox-group test refactor

src/components/list/styles/material.scss
=> list color style fixed

src/components/paginator/README.rst, src/components/paginator/components/paginator.js, src/components/paginator/styles/_shared.scss, tests/components/paginator/paginator.spec.js
Test cubiertos para el paginator, pendiente de documentación
=> paginator test coverage

src/components/select/styles/_shared.scss, src/showcase/screens/base/select/selectDemo.js
=> theme paint relative

src/components/radio/styles/_shared.scss, src/components/radio/styles/material.scss
Relative path del theme arreglado
=> theme paint relative path

src/components/paginator/styles/_shared.scss
=> theme paint relative path fix

src/components/tooltip/styles/_shared.scss
Arreglado en path relativo para el theme
=> base theme relative path fix

src/components/checkbox/styles/_shared.scss
path relativo del theme arreglado
=> theme relative path fix

src/components/tabs/styles/_shared.scss
=> relative theme path added

src/components/select/styles/_shared.scss
=> select shared styles improved

src/components/checkbox/styles/_shared.scss, src/showcase/screens/base/checkbox/checkboxDemo.js
Estilos mejorados para el checkbox
=> checkbox styles improved

src/components/input/styles/_shared.scss, src/components/input/styles/material.scss, src/showcase/screens/base/input/inputDemo.js
Vinculo a documentación añadido
=> Reference added

src/components/card/README.rst, src/showcase/screens/base/card/cardDemo.js, src/showcase/screens/base/root.routes.js
Agregada la tabla de documentación de slots
=> Reference link and documentation updated with slots table

src/components/card/README.rst
Arreglos para la tabla de slots
=> slots table fix

src/components/alert/components/alert.js, src/components/alert/styles/_shared.scss, src/components/alert/styles/material.scss, src/showcase/screens/base/alert/alertDemo.js
Se agrega contentBackground y contentColor para aplicar el tema al div con clase .ark-alert__content. se hace un arreglo de los estilos de material, incluyendo el elevetion y se agrega border-radius a 5px
=> Style theme working correctly

src/components/accordion/components/accordion.tab.js, src/components/accordion/styles/ark.css, src/components/button/styles/ark.css, src/showcase/design/screens/base/accordion/accordionDemo.js, src/showcase/design/screens/base/root.component.js, src/showcase/index.html
The style was changed on Accordion and Sidebar components.
=> Update accordion and sidebar style
